### ISSUE TITLE
The calendar is not working.

### ISSUE THREAD

**Issue by KenTauchi** [togami2864/react-ts-github-calendar#1]
Hi,

The calendar is not working now. I see an error in the console saying 

"TypeError: Cannot set property 'innerHTML' of null"

The Bloggify/github-calendar repo actually just fixed the issue, but this repo is not working yet. 
I would appreciate it if you could fix the bug by referring to the original repo. And Thank you for your fantastic work.

**Comment by togami2864** [comment]
@KenTauchi Thank you for reporting !
I'll work on it.
